name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Python technology
      run: sudo apt-get install -y python3-setuptools
    
    - name: Install Conan
      run: pip3 install -U wheel --user && pip3 install conan && sudo ln -s ~/.local/bin/conan /usr/bin/conan

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    
    - name: Run Conan install
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: conan install $GITHUB_WORKSPACE -pr=$GITHUB_WORKSPACE/conan_profile

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE -V
